Repository IIM-Creative-Technology/NODEJS-SOCKETIO-IIM-A4-DW2-EQUIPE1, pull requests merged in 2022-04, with the labels that each got.

#1 Project initialization
  .gitignore
  app.js
  package-lock.json
  package.json
Labels: express

#5 [Docs] Update Readme
  README.md
Labels: Readme

#7 [Templating] Add PR Template and update readMe
  .github/pull_request_template.md
  README.md
  readMe.md
Labels: documentation, feature, DONE

#12 [TEST] Init Jest
  package-lock.json
  package.json
  src/test/sum.js
  src/test/sum.test.js
Labels: feature, DONE

#14 [Cors] resolved cors errors
  app.js
  package-lock.json
  package.json
Labels: feature, DONE

#16 [CRUD] Create user crud
  .env.example
  Dockerfile
  app.js
  docker-compose.yml
  docs/swagger.json
  package-lock.json
  package.json
  src/controllers/UserController.js
  src/middleware/authentication.js
  src/routes/users.js
  src/services/authentication/authenticationToken.js
  template/login.html
  template/register.html
  template/style/login.css
Labels: feature

#19 [PROD] First MEP
  .dockerignore
  .env.example
  .github/pull_request_template.md
  .github/workflows/deploy-develop.yml
  .github/workflows/deploy-main.yml
  .gitignore
  Dockerfile
  README.md
  app.js
  docker-compose.yml
  docs/swagger.js
  docs/swagger.json
  package-lock.json
  package.json
  readMe.md
  src/config/abstract/roleEnum.js
  src/config/db.js
  src/controllers/UserController.js
  src/data/test/simpleModel.js
  src/data/userModel.js
  src/middleware/authentication.js
  src/routes/users.js
  src/services/UserService.js
  src/services/authentication/authenticationToken.js
  src/test/db/db.test.js
  src/test/sum.js
  src/test/sum.test.js
  template/index.html
  template/login.html
  template/register.html
  template/style/login.css
Labels: MEP

#20 [FIX] some fix for heroku db
  package.json
  src/config/db.js
  src/routes/users.js
  src/services/UserService.js
Labels: MEP

#18 [Feature] chat
  app.js
  package-lock.json
  package.json
  src/routes/ping.js
  template/chat/chat.html
  template/index.html
  template/style.css
Labels: WIP

#31 Feature/api get all users
  docs/swagger.json
  src/controllers/UserController.js
  src/routes/users.js
Labels: feature, DONE
